# frozen_string_literal: true

source "https://rubygems.org"
gem "capybara", "3.32.1"
gem "rspec", "3.9.0"
#needs selenium since capybara uses selenium
gem "selenium-webdriver", "3.142.7"
#needs for capybara as well, capybara uses resources from ffi
gem "ffi", "1.12.2"
